name: CI

on:
  push:
    branches: [ "solutions" ]
  pull_request:
    branches: [ "solutions" ]

jobs:
  build:
    name: Build and Test All List Exercises
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build CI
        run: 
          xcodebuild -scheme CI build
      - name: Test CI
        run: 
          xcodebuild -scheme CI test
